import { NextRequest, NextResponse } from "next/server"
import { requireAdmin } from "@/lib/auth"
import { websiteToHTML, type GeneratedWebsite } from "@/lib/website-builder"
import { projectToNextJS, projectToPHP } from '@/lib/project-exporters'
import type { WebsiteProject } from '@/app/admin/website-builder/builder-types'
import { promises as fs } from "fs"
import path from "path"

const SITES_DIR = path.join(process.cwd(), "public", "generated-sites")

async function ensureDir() {
  try {
    await fs.mkdir(SITES_DIR, { recursive: true })
  } catch {
    // already exists
  }
}

function slugify(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 40)
}

export async function POST(req: NextRequest) {
  if (!requireAdmin(req)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  try {
    const { website, format = 'html' } = (await req.json()) as { website: GeneratedWebsite; format?: 'html' | 'nextjs' | 'php' }

    const isNewFormat = website && 'pages' in website && Array.isArray((website as unknown as Record<string, unknown>).pages)
    const projectData = website as unknown as WebsiteProject

    // Determine name for slugging
    const nameForSlug = isNewFormat
      ? (projectData.name || 'website')
      : (website as GeneratedWebsite)?.businessName || 'website'

    if (!nameForSlug) {
      return NextResponse.json({ error: "website object is required" }, { status: 400 })
    }

    await ensureDir()

    const slug = slugify(nameForSlug)
    const timestamp = Date.now()
    const baseName = `${slug}-${timestamp}`

    // Determine file extension and content based on format
    let ext: string
    let content: string

    if (format === 'nextjs') {
      if (!isNewFormat) {
        return NextResponse.json({ error: 'Next.js export requires the new website builder format.' }, { status: 400 })
      }
      content = projectToNextJS(projectData)
      ext = '.tsx'
    } else if (format === 'php') {
      if (isNewFormat) {
        content = projectToPHP(projectData)
      } else {
        const htmlContent = websiteToHTML(website)
        content = `<?php\n// Generated by KVL TECH Website Builder\n$site_name = "${(website as GeneratedWebsite).businessName}";\n?>\n` + htmlContent.replace('<title>', '<title><?php echo htmlspecialchars($site_name); ?> | ')
      }
      ext = '.php'
    } else {
      // Default: HTML
      content = isNewFormat
        ? (await import('@/lib/project-exporters')).projectToHTML(projectData)
        : websiteToHTML(website)
      ext = '.html'
    }

    const jsonPath = path.join(SITES_DIR, `${baseName}.json`)
    const contentPath = path.join(SITES_DIR, `${baseName}${ext}`)

    await Promise.all([
      fs.writeFile(jsonPath, JSON.stringify(website, null, 2), "utf-8"),
      fs.writeFile(contentPath, content, "utf-8"),
    ])

    const previewUrl = `/generated-sites/${baseName}${ext}`

    return NextResponse.json({
      jsonPath: `/generated-sites/${baseName}.json`,
      htmlPath: previewUrl,
      previewUrl,
      fileName: baseName,
      format,
      savedAt: new Date().toISOString(),
    })
  } catch (err) {
    const message = err instanceof Error ? err.message : "Save failed"
    console.error("[website-builder/save] error:", err)
    return NextResponse.json({ error: message }, { status: 500 })
  }
}

export async function GET(req: NextRequest) {
  if (!requireAdmin(req)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  try {
    await ensureDir()

    const files = await fs.readdir(SITES_DIR)
    const jsonFiles = files.filter((f) => f.endsWith(".json"))

    const sites = await Promise.all(
      jsonFiles.map(async (file) => {
        const filePath = path.join(SITES_DIR, file)
        const stat = await fs.stat(filePath)
        const baseName = file.replace(".json", "")

        let businessName = baseName
        let industry = ""
        let tagline = ""

        try {
          const raw = await fs.readFile(filePath, "utf-8")
          const data = JSON.parse(raw) as GeneratedWebsite
          businessName = data.businessName || baseName
          industry = data.industry || ""
          tagline = data.tagline || ""
        } catch {
          // skip parse errors
        }

        return {
          fileName: baseName,
          businessName,
          industry,
          tagline,
          jsonUrl: `/generated-sites/${baseName}.json`,
          htmlUrl: `/generated-sites/${baseName}.html`,
          previewUrl: `/generated-sites/${baseName}.html`,
          savedAt: stat.mtime.toISOString(),
          size: stat.size,
        }
      })
    )

    // Sort newest first
    sites.sort((a, b) => new Date(b.savedAt).getTime() - new Date(a.savedAt).getTime())

    return NextResponse.json({ sites, count: sites.length })
  } catch (err) {
    const message = err instanceof Error ? err.message : "List failed"
    return NextResponse.json({ error: message }, { status: 500 })
  }
}
