// Note: This file was generated by KVL TECH Website Builder
// Pure string generators — no external dependencies, no async.

import type { WebsiteProject, BuilderElement, Section, GlobalStyles } from '@/app/admin/website-builder/builder-types';

// ─── Shared helpers ────────────────────────────────────────────────────────────

function cssToString(styles: Record<string, string | undefined>): string {
  return Object.entries(styles)
    .filter(([, v]) => v !== undefined && v !== '')
    .map(([k, v]) => `${k.replace(/([A-Z])/g, '-$1').toLowerCase()}:${v}`)
    .join(';');
}

function cssToJSXObject(styles: Record<string, string | undefined>): string {
  const entries = Object.entries(styles).filter(([, v]) => v !== undefined && v !== '');
  if (!entries.length) return '{}';
  const props = entries.map(([k, v]) => {
    const camel = k.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
    return `${camel}: '${String(v).replace(/'/g, "\\'")}'`;
  });
  return `{ ${props.join(', ')} }`;
}

// ══════════════════════════════════════════════════════════════════════════════
// FUNCTION 1: projectToNextJS
// ══════════════════════════════════════════════════════════════════════════════

function elementToJSX(el: BuilderElement, gs: GlobalStyles): string {
  const cfg = el.config as Record<string, unknown>;
  const styleObj = cssToJSXObject(el.styles || {});

  switch (el.type) {
    case 'heading': {
      const level = (cfg.level as number) || 2;
      const text = (cfg.text as string) || 'Heading';
      const headingSt = cssToJSXObject({ fontFamily: `'${gs.headingFont}',sans-serif`, ...el.styles });
      return `<h${level} style={${headingSt}}>${text}</h${level}>`;
    }

    case 'paragraph':
      return `<p style={{ lineHeight: '1.7', ...${styleObj} }}>${cfg.text || ''}</p>`;

    case 'richtext':
      return `<div style={${styleObj}} dangerouslySetInnerHTML={{ __html: ${JSON.stringify(cfg.html || '')} }} />`;

    case 'quote':
      return `<blockquote style={{ borderLeft: '4px solid ${gs.primaryColor}', paddingLeft: '1.5rem', fontStyle: 'italic', ...${styleObj} }}>${cfg.text || ''}</blockquote>`;

    case 'list': {
      const items = (cfg.items as string[]) || [];
      const tag = cfg.ordered ? 'ol' : 'ul';
      const itemsJSX = items.map(i => `<li>${i}</li>`).join('');
      return `<${tag} style={{ paddingLeft: '1.5rem', lineHeight: '2', ...${styleObj} }}>${itemsJSX}</${tag}>`;
    }

    case 'button': {
      const variant = (cfg.variant as string) || 'primary';
      const bgMap: Record<string, string> = { primary: gs.primaryColor, secondary: gs.secondaryColor, outline: 'transparent', ghost: 'transparent', link: 'transparent' };
      const colorMap: Record<string, string> = { primary: '#fff', secondary: '#fff', outline: gs.primaryColor, ghost: gs.primaryColor, link: gs.primaryColor };
      const border = variant === 'outline' ? `2px solid ${gs.primaryColor}` : 'none';
      const size = (cfg.size as string) || 'md';
      const pMap: Record<string, string> = { sm: '6px 16px', md: '10px 24px', lg: '14px 32px' };
      const bg = bgMap[variant] || gs.primaryColor;
      const color = colorMap[variant] || '#fff';
      const pad = pMap[size] || pMap['md'];
      return `<Link href="${cfg.href || '#'}" style={{ display: 'inline-block', background: '${bg}', color: '${color}', border: '${border}', padding: '${pad}', borderRadius: '6px', fontWeight: 600, textDecoration: 'none', ...${styleObj} }}>${cfg.label || 'Click Here'}</Link>`;
    }

    case 'buttongroup': {
      const buttons = (cfg.buttons as Array<{ label: string; href: string; variant: string; size: string }>) || [];
      const btnJSX = buttons.map(btn => {
        const v = btn.variant || 'primary';
        const bgMap: Record<string, string> = { primary: gs.primaryColor, secondary: gs.secondaryColor, outline: 'transparent', ghost: 'transparent', link: 'transparent' };
        const colorMap: Record<string, string> = { primary: '#fff', secondary: '#fff', outline: gs.primaryColor, ghost: gs.primaryColor, link: gs.primaryColor };
        const border = v === 'outline' ? `2px solid ${gs.primaryColor}` : 'none';
        const s = btn.size || 'md';
        const pMap: Record<string, string> = { sm: '6px 16px', md: '10px 24px', lg: '14px 32px' };
        return `<Link href="${btn.href || '#'}" style={{ display: 'inline-block', background: '${bgMap[v] || gs.primaryColor}', color: '${colorMap[v] || '#fff'}', border: '${border}', padding: '${pMap[s] || pMap['md']}', borderRadius: '6px', fontWeight: 600, textDecoration: 'none' }}>${btn.label || 'Button'}</Link>`;
      }).join('\n        ');
      return `<div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap', alignItems: 'center', ...${styleObj} }}>
        ${btnJSX}
      </div>`;
    }

    case 'image':
      return `<div style={${styleObj}}><img src="${cfg.src || ''}" alt="${cfg.alt || ''}" style={{ width: '100%', height: '100%', objectFit: '${cfg.fit || 'cover'}' }} /></div>`;

    case 'gallery': {
      const images = (cfg.images as Array<{ src: string; alt: string }>) || [];
      const cols = (cfg.columns as number) || 3;
      const gap = (cfg.gap as number) || 16;
      const imgItems = images.map((img, i) =>
        `<div key={${i}} style={{ overflow: 'hidden', borderRadius: '8px', aspectRatio: '4/3' }}><img src="${img.src}" alt="${img.alt || ''}" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /></div>`
      ).join('\n          ');
      return `<div style={{ display: 'grid', gridTemplateColumns: 'repeat(${cols}, 1fr)', gap: '${gap}px', ...${styleObj} }}>
          ${imgItems}
        </div>`;
    }

    case 'slider': {
      const safeId = el.id.replace(/[^a-zA-Z0-9]/g, '_');
      return `<SliderComponent_${safeId} />`;
    }

    case 'video': {
      const src = (cfg.src as string) || '';
      if (src.includes('youtube') || src.includes('youtu.be')) {
        const vid = src.includes('youtu.be')
          ? src.split('youtu.be/')[1]?.split('?')[0]
          : src.split('v=')[1]?.split('&')[0];
        return `<div style={{ position: 'relative', paddingBottom: '56.25%', height: 0, overflow: 'hidden', borderRadius: 8, ...${styleObj} }}><iframe src="https://www.youtube.com/embed/${vid || ''}" style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', border: 0 }} allowFullScreen title="YouTube video" /></div>`;
      }
      if (src.includes('vimeo.com')) {
        const vid = src.split('vimeo.com/')[1]?.split('?')[0];
        return `<div style={{ position: 'relative', paddingBottom: '56.25%', height: 0, overflow: 'hidden', borderRadius: 8, ...${styleObj} }}><iframe src="https://player.vimeo.com/video/${vid || ''}" style={{ position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', border: 0 }} allowFullScreen title="Vimeo video" /></div>`;
      }
      return `<video src="${src}" ${cfg.controls !== false ? 'controls' : ''} ${cfg.autoPlay ? 'autoPlay' : ''} ${cfg.muted ? 'muted' : ''} ${cfg.loop ? 'loop' : ''} style={{ width: '100%', ...${styleObj} }} />`;
    }

    case 'marquee': {
      const items = (cfg.items as string[]) || [];
      const sep = (cfg.separator as string) || ' · ';
      const speed = (cfg.speed as number) || 30;
      const text = [...items, ...items].join(sep);
      return `<div style={{ overflow: 'hidden', whiteSpace: 'nowrap', ...${styleObj} }}><span style={{ display: 'inline-block', animation: \`marqueeScroll ${speed}s linear infinite\` }}>${text}</span></div>`;
    }

    case 'divider':
      return `<hr style={{ border: 'none', borderTop: '1px solid rgba(0,0,0,0.15)', margin: '1rem 0', ...${styleObj} }} />`;

    case 'spacer':
      return `<div style={{ height: '${cfg.height || 48}px' }} />`;

    case 'icon':
      return `<div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '1rem', ...${styleObj} }}><span style={{ fontSize: '${(cfg.size as number) || 48}px', color: '${(cfg.color as string) || gs.primaryColor}' }}>&#9733;</span></div>`;

    case 'iconbox': {
      const align = (cfg.align as string) || 'center';
      return `<div style={{ textAlign: '${align}', padding: '2rem 1.5rem', ...${styleObj} }}>
        <div style={{ fontSize: '2.5rem', marginBottom: '1rem' }}>${cfg.icon || '★'}</div>
        <h4 style={{ fontWeight: 700, fontSize: '1.25rem', marginBottom: '0.5rem', fontFamily: "'${gs.headingFont}',sans-serif" }}>${cfg.title || ''}</h4>
        <p style={{ color: '#666', lineHeight: 1.7 }}>${cfg.description || ''}</p>
      </div>`;
    }

    case 'card': {
      const title = (cfg.title as string) || 'Card Title';
      const desc = (cfg.description as string) || '';
      const image = cfg.image as string | undefined;
      const link = cfg.link as string | undefined;
      const badge = cfg.badge as string | undefined;
      return `<div style={{ background: '#fff', borderRadius: 12, overflow: 'hidden', boxShadow: '0 4px 24px rgba(0,0,0,0.08)', ...${styleObj} }}>
        ${image ? `<div style={{ aspectRatio: '16/9', overflow: 'hidden' }}><img src="${image}" alt="${title}" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /></div>` : ''}
        <div style={{ padding: '1.5rem' }}>
          ${badge ? `<span style={{ display: 'inline-block', background: '${gs.primaryColor}', color: '#fff', fontSize: '0.7rem', fontWeight: 700, padding: '2px 10px', borderRadius: 999, marginBottom: '0.75rem', textTransform: 'uppercase' as const }}>${badge}</span>` : ''}
          <h4 style={{ fontWeight: 700, fontSize: '1.1rem', marginBottom: '0.5rem' }}>${title}</h4>
          <p style={{ color: '#666', lineHeight: 1.6, fontSize: '0.9rem' }}>${desc}</p>
          ${link ? `<Link href="${link}" style={{ display: 'inline-block', marginTop: '1rem', color: '${gs.primaryColor}', fontWeight: 600, fontSize: '0.875rem', textDecoration: 'none' }}>Learn more →</Link>` : ''}
        </div>
      </div>`;
    }

    case 'counter': {
      const items = (cfg.items as Array<{ value: number; label: string; prefix?: string; suffix?: string }>) || [];
      const itemsJSX = items.map((it, i) =>
        `<div key={${i}} style={{ textAlign: 'center' }}><div style={{ fontSize: '3rem', fontWeight: 800, color: '${gs.primaryColor}' }}>${it.prefix || ''}${it.value}${it.suffix || ''}</div><div style={{ color: '#666', marginTop: '0.5rem' }}>${it.label}</div></div>`
      ).join('\n          ');
      return `<div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: '3rem', padding: '2rem', ...${styleObj} }}>
          ${itemsJSX}
        </div>`;
    }

    case 'countdown': {
      const safeId = el.id.replace(/[^a-zA-Z0-9]/g, '_');
      return `<CountdownComponent_${safeId} />`;
    }

    case 'progress': {
      const items = (cfg.items as Array<{ label: string; value: number; color?: string }>) || [];
      const bars = items.map((it, i) =>
        `<div key={${i}} style={{ marginBottom: '1.5rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}><span style={{ fontWeight: 600 }}>${it.label}</span><span style={{ color: '${it.color || gs.primaryColor}', fontWeight: 700 }}>${it.value}%</span></div>
            <div style={{ background: '#eee', borderRadius: '999px', height: '8px' }}><div style={{ background: '${it.color || gs.primaryColor}', borderRadius: '999px', height: '8px', width: '${it.value}%', transition: 'width 1s' }} /></div>
          </div>`
      ).join('\n          ');
      return `<div style={{ maxWidth: '700px', margin: '0 auto', padding: '1rem', ...${styleObj} }}>
          ${bars}
        </div>`;
    }

    case 'testimonial': {
      const rating = (cfg.rating as number) || 5;
      const stars = '★'.repeat(Math.min(5, Math.max(0, rating)));
      return `<div style={{ maxWidth: '700px', margin: '0 auto', background: '#fff', borderRadius: '12px', padding: '2.5rem', boxShadow: '0 4px 24px rgba(0,0,0,.08)', ...${styleObj} }}>
        <div style={{ color: '#F59E0B', fontSize: '1.25rem', marginBottom: '1rem' }}>${stars}</div>
        <p style={{ fontSize: '1.1rem', color: '#555', fontStyle: 'italic', marginBottom: '1.5rem' }}>&ldquo;${cfg.text || ''}&rdquo;</p>
        <strong>${cfg.name || ''}</strong> <span style={{ color: '#888', fontSize: '0.875rem' }}>&nbsp;&middot;&nbsp;${cfg.role || ''}</span>
      </div>`;
    }

    case 'pricing': {
      const plans = (cfg.plans as Array<{ name: string; price: string; period: string; features: string[]; cta: { label: string; href: string }; highlighted: boolean; badge?: string }>) || [];
      const plansJSX = plans.map((p, i) => {
        const featuresJSX = (p.features || []).map((f, j) => `<li key={${j}} style={{ padding: '0.25rem 0' }}>✓ ${f}</li>`).join('');
        return `<div key={${i}} style={{ flex: '1 1 280px', maxWidth: '320px', background: '${p.highlighted ? gs.secondaryColor : '#fff'}', color: '${p.highlighted ? '#fff' : '#333'}', border: '${p.highlighted ? `2px solid ${gs.primaryColor}` : '1px solid #eee'}', borderRadius: '16px', padding: '2rem', position: 'relative' }}>
            ${p.badge ? `<span style={{ position: 'absolute', top: -12, right: 16, background: '${gs.primaryColor}', color: '#fff', padding: '2px 12px', borderRadius: '999px', fontSize: '0.75rem', fontWeight: 700 }}>${p.badge}</span>` : ''}
            <h3 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '0.5rem' }}>${p.name}</h3>
            <div style={{ fontSize: '2.5rem', fontWeight: 800, color: '${gs.primaryColor}', marginBottom: '0.25rem' }}>${p.price}</div>
            <div style={{ color: '#888', fontSize: '0.875rem', marginBottom: '1.5rem' }}>${p.period}</div>
            <ul style={{ listStyle: 'none', padding: 0, marginBottom: '2rem' }}>${featuresJSX}</ul>
            <Link href="${p.cta?.href || '#'}" style={{ display: 'block', textAlign: 'center', padding: '0.75rem', borderRadius: '8px', background: '${p.highlighted ? gs.primaryColor : 'transparent'}', color: '${p.highlighted ? gs.secondaryColor : gs.primaryColor}', border: '2px solid ${gs.primaryColor}', fontWeight: 700, textDecoration: 'none' }}>${p.cta?.label || 'Get Started'}</Link>
          </div>`;
      }).join('\n          ');
      return `<div style={{ display: 'flex', flexWrap: 'wrap', gap: '1.5rem', justifyContent: 'center', padding: '2rem 0', ...${styleObj} }}>
          ${plansJSX}
        </div>`;
    }

    case 'accordion': {
      const safeId = el.id.replace(/[^a-zA-Z0-9]/g, '_');
      return `<AccordionComponent_${safeId} />`;
    }

    case 'tabs': {
      const safeId = el.id.replace(/[^a-zA-Z0-9]/g, '_');
      return `<TabsComponent_${safeId} />`;
    }

    case 'form': {
      const fields = (cfg.fields as Array<{ id: string; type: string; label: string; placeholder?: string; required?: boolean; options?: string[] }>) || [];
      const fieldsJSX = fields.map(f => {
        const req = f.required ? ' required' : '';
        if (f.type === 'textarea') {
          return `<div key="${f.id}" style={{ marginBottom: '1rem' }}><label style={{ display: 'block', marginBottom: '0.25rem', fontWeight: 500 }}>${f.label}</label><textarea name="${f.id}" placeholder="${f.placeholder || ''}"${req} rows={4} style={{ width: '100%', padding: '0.5rem 0.75rem', border: '1px solid #ddd', borderRadius: '6px', fontFamily: 'inherit', resize: 'vertical' }} /></div>`;
        }
        if (f.type === 'select') {
          const opts = (f.options || []).map((o, oi) => `<option key={${oi}}>${o}</option>`).join('');
          return `<div key="${f.id}" style={{ marginBottom: '1rem' }}><label style={{ display: 'block', marginBottom: '0.25rem', fontWeight: 500 }}>${f.label}</label><select name="${f.id}"${req} style={{ width: '100%', padding: '0.5rem 0.75rem', border: '1px solid #ddd', borderRadius: '6px' }}>${opts}</select></div>`;
        }
        if (f.type === 'checkbox') {
          return `<div key="${f.id}" style={{ marginBottom: '1rem' }}><label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer' }}><input type="checkbox" name="${f.id}" /><span style={{ fontSize: '0.875rem' }}>${f.placeholder || f.label}</span></label></div>`;
        }
        return `<div key="${f.id}" style={{ marginBottom: '1rem' }}><label style={{ display: 'block', marginBottom: '0.25rem', fontWeight: 500 }}>${f.label}</label><input type="${f.type}" name="${f.id}" placeholder="${f.placeholder || ''}"${req} style={{ width: '100%', padding: '0.5rem 0.75rem', border: '1px solid #ddd', borderRadius: '6px' }} /></div>`;
      }).join('\n          ');
      return `<form style={{ maxWidth: '600px', margin: '0 auto', ...${styleObj} }} onSubmit={e => e.preventDefault()}>
          ${fieldsJSX}
          <button type="submit" style={{ background: '${gs.primaryColor}', color: '#fff', border: 'none', padding: '0.75rem 2.5rem', borderRadius: '8px', fontWeight: 700, fontSize: '1rem', cursor: 'pointer' }}>${cfg.submitLabel || 'Send'}</button>
        </form>`;
    }

    case 'map': {
      const addr = encodeURIComponent((cfg.address as string) || 'India');
      const zoom = (cfg.zoom as number) || 14;
      const height = (cfg.height as number) || 400;
      return `<div style={{ borderRadius: '12px', overflow: 'hidden', ...${styleObj} }}><iframe src="https://maps.google.com/maps?q=${addr}&output=embed&z=${zoom}" width="100%" height={${height}} style={{ border: 0 }} allowFullScreen loading="lazy" title="Google Map" /></div>`;
    }

    case 'social': {
      const links = (cfg.links as Array<{ platform: string; url: string }>) || [];
      const colors: Record<string, string> = { facebook: '#1877F2', instagram: '#E4405F', twitter: '#1DA1F2', youtube: '#FF0000', linkedin: '#0A66C2', whatsapp: '#25D366', tiktok: '#010101', pinterest: '#E60023' };
      const icons: Record<string, string> = { facebook: 'f', instagram: '📷', twitter: '𝕏', youtube: '▶', linkedin: 'in', whatsapp: 'W', tiktok: '♪', pinterest: 'P' };
      const linksJSX = links.map((l, i) =>
        `<a key={${i}} href="${l.url}" style={{ width: 44, height: 44, borderRadius: '50%', background: '${colors[l.platform] || '#666'}', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontWeight: 700, fontSize: '0.875rem', textDecoration: 'none' }}>${icons[l.platform] || l.platform[0]?.toUpperCase() || '?'}</a>`
      ).join('\n          ');
      return `<div style={{ display: 'flex', gap: '0.75rem', flexWrap: 'wrap', justifyContent: 'center', ...${styleObj} }}>
          ${linksJSX}
        </div>`;
    }

    case 'navbar': {
      const links = (cfg.links as Array<{ label: string; href: string }>) || [];
      const linksJSX = links.map((l, i) =>
        `<Link key={${i}} href="${l.href}" style={{ color: '#fff', textDecoration: 'none', fontSize: '0.9rem', fontWeight: 500 }}>${l.label}</Link>`
      ).join('\n            ');
      return `<nav style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '1rem 2rem', background: '${gs.secondaryColor}', color: '#fff', ...${styleObj} }}>
          <span style={{ fontWeight: 800, fontSize: '1.25rem', color: '${gs.primaryColor}', fontFamily: "'${gs.headingFont}',sans-serif" }}>${cfg.logoText || 'Brand'}</span>
          <div style={{ display: 'flex', gap: '1.5rem', alignItems: 'center' }}>
            ${linksJSX}
          </div>
        </nav>`;
    }

    case 'footer': {
      const columns = (cfg.columns as Array<{ heading: string; links: Array<{ label: string; href: string }> }>) || [];
      const socials = (cfg.socials as Array<{ platform: string; url: string }>) || [];
      const socColors: Record<string, string> = { facebook: '#1877F2', instagram: '#E4405F', twitter: '#1DA1F2', youtube: '#FF0000', linkedin: '#0A66C2', whatsapp: '#25D366' };
      const colsJSX = columns.map((col, ci) => {
        const colLinks = col.links.map((l, li) =>
          `<li key={${li}} style={{ marginBottom: '0.5rem' }}><Link href="${l.href}" style={{ color: '#aaa', textDecoration: 'none', fontSize: '0.875rem' }}>${l.label}</Link></li>`
        ).join('');
        return `<div key={${ci}} style={{ flex: '1 1 160px' }}><h5 style={{ fontWeight: 700, marginBottom: '1rem', color: '${gs.primaryColor}' }}>${col.heading}</h5><ul style={{ listStyle: 'none', padding: 0 }}>${colLinks}</ul></div>`;
      }).join('\n            ');
      const socialsJSX = socials.map((s, si) =>
        `<a key={${si}} href="${s.url}" style={{ width: 36, height: 36, borderRadius: '50%', background: '${socColors[s.platform] || '#666'}', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', color: '#fff', textDecoration: 'none', fontSize: '0.75rem' }}>${s.platform[0]?.toUpperCase() || '?'}</a>`
      ).join('');
      return `<footer style={{ background: '${gs.secondaryColor}', color: '#fff', padding: '3rem 2rem 1.5rem', ...${styleObj} }}>
          <div style={{ maxWidth: '1280px', margin: '0 auto' }}>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '2rem', marginBottom: '2rem' }}>
              ${colsJSX}
            </div>
            ${cfg.tagline ? `<p style={{ color: '#888', marginBottom: '1rem', fontSize: '0.875rem' }}>${cfg.tagline}</p>` : ''}
            <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1rem' }}>${socialsJSX}</div>
            <div style={{ borderTop: '1px solid rgba(255,255,255,.1)', paddingTop: '1rem', color: '#555', fontSize: '0.8rem' }}>&copy; ${cfg.copyright || ''}</div>
          </div>
        </footer>`;
    }

    case 'hero': {
      const cta = cfg.cta as { label: string; href: string } | undefined;
      const cta2 = cfg.secondaryCta as { label: string; href: string } | undefined;
      const align = (cfg.align as string) || 'center';
      const overlay = (cfg.overlay as number) || 50;
      const bgImg = cfg.bgImage as string | undefined;
      const justifyContent = align === 'center' ? 'center' : align === 'right' ? 'flex-end' : 'flex-start';
      return `<div style={{ position: 'relative', minHeight: '80vh', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', ...${styleObj} }}>
        ${bgImg ? `<img src="${bgImg}" alt="" style={{ position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' }} />` : ''}
        <div style={{ position: 'absolute', inset: 0, background: \`rgba(11,20,55,${overlay / 100})\` }} />
        <div style={{ position: 'relative', textAlign: '${align}', color: '#fff', padding: '4rem 2rem', maxWidth: '900px', width: '100%' }}>
          ${cfg.subheading ? `<p style={{ color: '${gs.primaryColor}', fontWeight: 600, letterSpacing: '0.1em', marginBottom: '1rem', textTransform: 'uppercase', fontSize: '0.875rem' }}>${cfg.subheading}</p>` : ''}
          <h1 style={{ fontSize: 'clamp(2rem,5vw,4rem)', fontWeight: 800, lineHeight: 1.1, marginBottom: '1.5rem', fontFamily: "'${gs.headingFont}',sans-serif" }}>${cfg.heading || 'Welcome'}</h1>
          ${cfg.text ? `<p style={{ fontSize: '1.25rem', opacity: 0.85, marginBottom: '2rem', maxWidth: '600px', marginLeft: 'auto', marginRight: 'auto' }}>${cfg.text}</p>` : ''}
          <div style={{ display: 'flex', gap: '1rem', justifyContent: '${justifyContent}', flexWrap: 'wrap' }}>
            ${cta ? `<Link href="${cta.href}" style={{ background: '${gs.primaryColor}', color: '#fff', padding: '0.875rem 2.5rem', borderRadius: '8px', fontWeight: 700, textDecoration: 'none', fontSize: '1.1rem' }}>${cta.label}</Link>` : ''}
            ${cta2 ? `<Link href="${cta2.href}" style={{ border: '2px solid rgba(255,255,255,.6)', color: '#fff', padding: '0.875rem 2.5rem', borderRadius: '8px', fontWeight: 700, textDecoration: 'none', fontSize: '1.1rem' }}>${cta2.label}</Link>` : ''}
          </div>
        </div>
      </div>`;
    }

    case 'cta': {
      const cta = cfg.cta as { label: string; href: string } | undefined;
      return `<div style={{ background: '${cfg.bgColor || gs.secondaryColor}', color: '#fff', textAlign: 'center', padding: '4rem 2rem', ...${styleObj} }}>
        <h2 style={{ fontSize: '2rem', fontWeight: 700, marginBottom: '1rem', fontFamily: "'${gs.headingFont}',sans-serif" }}>${cfg.heading || ''}</h2>
        <p style={{ opacity: 0.8, marginBottom: '2rem', fontSize: '1.1rem' }}>${cfg.text || ''}</p>
        ${cta ? `<Link href="${cta.href}" style={{ background: '${gs.primaryColor}', color: '#fff', padding: '0.875rem 2.5rem', borderRadius: '8px', fontWeight: 700, textDecoration: 'none', fontSize: '1.1rem' }}>${cta.label}</Link>` : ''}
      </div>`;
    }

    default:
      return `<div style={{ padding: '1rem', border: '1px dashed #ccc', color: '#999', textAlign: 'center' }}>{/* ${el.type} */}</div>`;
  }
}

// ── Collect all interactive elements from a page ─────────────────────────────

interface InteractiveCollections {
  sliders: Array<{ id: string; config: Record<string, unknown> }>;
  countdowns: Array<{ id: string; config: Record<string, unknown> }>;
  accordions: Array<{ id: string; config: Record<string, unknown> }>;
  tabs: Array<{ id: string; config: Record<string, unknown> }>;
}

function collectInteractiveElements(sections: Section[]): InteractiveCollections {
  const sliders: Array<{ id: string; config: Record<string, unknown> }> = [];
  const countdowns: Array<{ id: string; config: Record<string, unknown> }> = [];
  const accordions: Array<{ id: string; config: Record<string, unknown> }> = [];
  const tabs: Array<{ id: string; config: Record<string, unknown> }> = [];

  for (const section of sections) {
    for (const col of section.columns) {
      for (const el of col.elements) {
        if (el.hidden) continue;
        const cfg = el.config as Record<string, unknown>;
        if (el.type === 'slider') sliders.push({ id: el.id, config: cfg });
        if (el.type === 'countdown') countdowns.push({ id: el.id, config: cfg });
        if (el.type === 'accordion') accordions.push({ id: el.id, config: cfg });
        if (el.type === 'tabs') tabs.push({ id: el.id, config: cfg });
      }
    }
  }
  return { sliders, countdowns, accordions, tabs };
}

// ── Build slider React component definition ───────────────────────────────────

function buildSliderComponent(id: string, config: Record<string, unknown>, gs: GlobalStyles): string {
  const safeId = id.replace(/[^a-zA-Z0-9]/g, '_');
  const slides = (config.slides as Array<{ src: string; alt?: string; heading?: string; text?: string }>) || [];
  const autoPlay = config.autoPlay !== false;
  const interval = (config.interval as number) || 4000;
  const arrows = config.arrows !== false;
  const dots = config.dots !== false;
  const total = slides.length || 1;

  const slidesJSX = slides.map((slide, i) =>
    `        <div key={${i}} style={{ minWidth: '100%', position: 'relative' }}>
          <img src="${slide.src || ''}" alt="${slide.alt || ''}" style={{ width: '100%', height: '500px', objectFit: 'cover' }} />
          ${slide.heading ? `<div style={{ position: 'absolute', bottom: '2rem', left: '2rem', color: '#fff' }}><h2 style={{ fontSize: '2rem', fontWeight: 800, textShadow: '0 2px 8px rgba(0,0,0,.5)' }}>${slide.heading}</h2>${slide.text ? `<p style={{ marginTop: '0.5rem', textShadow: '0 1px 4px rgba(0,0,0,.5)' }}>${slide.text}</p>` : ''}</div>` : ''}
        </div>`
  ).join('\n');

  const dotsJSX = dots ? `<div style={{ position: 'absolute', bottom: '1rem', left: '50%', transform: 'translateX(-50%)', display: 'flex', gap: '0.5rem' }}>
        {Array.from({ length: ${total} }).map((_, i) => (
          <button key={i} onClick={() => setCurrent_${safeId}(i)} style={{ width: 10, height: 10, borderRadius: '50%', border: 'none', background: i === current_${safeId} ? '#fff' : 'rgba(255,255,255,.5)', cursor: 'pointer', padding: 0 }} />
        ))}
      </div>` : '';

  const arrowsJSX = arrows ? `<button onClick={() => setCurrent_${safeId}(s => (s - 1 + ${total}) % ${total})} style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)', background: 'rgba(0,0,0,.5)', color: '#fff', border: 'none', borderRadius: '50%', width: 40, height: 40, cursor: 'pointer', fontSize: '1.25rem' }}>&#8249;</button>
      <button onClick={() => setCurrent_${safeId}(s => (s + 1) % ${total})} style={{ position: 'absolute', right: '1rem', top: '50%', transform: 'translateY(-50%)', background: 'rgba(0,0,0,.5)', color: '#fff', border: 'none', borderRadius: '50%', width: 40, height: 40, cursor: 'pointer', fontSize: '1.25rem' }}>&#8250;</button>` : '';

  void gs;

  return `function SliderComponent_${safeId}() {
  const [current_${safeId}, setCurrent_${safeId}] = useState(0);
  useEffect(() => {
    ${autoPlay ? `const t = setInterval(() => setCurrent_${safeId}(s => (s + 1) % ${total}), ${interval}); return () => clearInterval(t);` : 'void undefined;'}
  }, []);
  return (
    <div style={{ position: 'relative', overflow: 'hidden' }}>
      <div style={{ display: 'flex', transition: 'transform 0.5s ease', transform: \`translateX(-\${current_${safeId} * 100}%)\` }}>
${slidesJSX}
      </div>
      ${arrowsJSX}
      ${dotsJSX}
    </div>
  );
}`;
}

// ── Build countdown React component definition ────────────────────────────────

function buildCountdownComponent(id: string, config: Record<string, unknown>, gs: GlobalStyles): string {
  const safeId = id.replace(/[^a-zA-Z0-9]/g, '_');
  const targetDate = (config.targetDate as string) || '2026-12-31';
  const label = (config.label as string) || '';

  return `function CountdownComponent_${safeId}() {
  const [time_${safeId}, setTime_${safeId}] = useState({ days: 0, hours: 0, minutes: 0, seconds: 0 });
  useEffect(() => {
    const target = new Date("${targetDate}").getTime();
    const update = () => {
      const diff = target - Date.now();
      if (diff <= 0) return;
      setTime_${safeId}({
        days: Math.floor(diff / 86400000),
        hours: Math.floor((diff % 86400000) / 3600000),
        minutes: Math.floor((diff % 3600000) / 60000),
        seconds: Math.floor((diff % 60000) / 1000),
      });
    };
    update();
    const t = setInterval(update, 1000);
    return () => clearInterval(t);
  }, []);
  const pad = (n: number) => String(n).padStart(2, '0');
  const units = ['days', 'hours', 'minutes', 'seconds'] as const;
  return (
    <div style={{ textAlign: 'center', padding: '2rem' }}>
      ${label ? `<p style={{ marginBottom: '1rem', fontWeight: 600, color: '${gs.primaryColor}' }}>${label}</p>` : ''}
      <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center' }}>
        {units.map(unit => (
          <div key={unit} style={{ background: '${gs.secondaryColor}', color: '#fff', borderRadius: '12px', padding: '1rem 1.5rem', minWidth: '80px' }}>
            <div style={{ fontSize: '2.5rem', fontWeight: 800, color: '${gs.primaryColor}' }}>{pad(time_${safeId}[unit])}</div>
            <div style={{ fontSize: '0.75rem', opacity: 0.7, textTransform: 'capitalize' }}>{unit}</div>
          </div>
        ))}
      </div>
    </div>
  );
}`;
}

// ── Build accordion React component definition ────────────────────────────────

function buildAccordionComponent(id: string, config: Record<string, unknown>, gs: GlobalStyles): string {
  const safeId = id.replace(/[^a-zA-Z0-9]/g, '_');
  const items = (config.items as Array<{ id: string; question: string; answer: string }>) || [];
  const firstId = items[0] ? JSON.stringify(items[0].id) : 'null';

  return `function AccordionComponent_${safeId}() {
  const [open_${safeId}, setOpen_${safeId}] = useState<string | null>(${firstId});
  const items_${safeId}: Array<{ id: string; question: string; answer: string }> = ${JSON.stringify(items)};
  return (
    <div style={{ maxWidth: '800px', margin: '0 auto' }}>
      {items_${safeId}.map(item => (
        <div key={item.id} style={{ border: '1px solid #eee', borderRadius: '8px', marginBottom: '0.5rem', overflow: 'hidden' }}>
          <button
            onClick={() => setOpen_${safeId}(open_${safeId} === item.id ? null : item.id)}
            style={{ width: '100%', textAlign: 'left', padding: '1rem 1.5rem', background: 'none', border: 'none', cursor: 'pointer', fontWeight: 600, fontSize: '1rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}
          >
            {item.question}
            <span style={{ fontSize: '1.25rem', color: '${gs.primaryColor}' }}>{open_${safeId} === item.id ? '−' : '+'}</span>
          </button>
          {open_${safeId} === item.id && (
            <div style={{ padding: '1rem 1.5rem', borderTop: '1px solid #eee', color: '#555', lineHeight: 1.7 }}>{item.answer}</div>
          )}
        </div>
      ))}
    </div>
  );
}`;
}

// ── Build tabs React component definition ─────────────────────────────────────

function buildTabsComponent(id: string, config: Record<string, unknown>, gs: GlobalStyles): string {
  const safeId = id.replace(/[^a-zA-Z0-9]/g, '_');
  const items = (config.items as Array<{ id: string; label: string; content: string }>) || [];
  const firstId = items[0] ? JSON.stringify(items[0].id) : "''";

  return `function TabsComponent_${safeId}() {
  const [tab_${safeId}, setTab_${safeId}] = useState<string>(${firstId});
  const items_${safeId}: Array<{ id: string; label: string; content: string }> = ${JSON.stringify(items)};
  return (
    <div>
      <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1rem', flexWrap: 'wrap' }}>
        {items_${safeId}.map(t => (
          <button
            key={t.id}
            onClick={() => setTab_${safeId}(t.id)}
            style={{ padding: '0.5rem 1.5rem', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 600, background: tab_${safeId} === t.id ? '${gs.primaryColor}' : 'transparent', color: tab_${safeId} === t.id ? '#fff' : '#555', transition: 'all 0.2s' }}
          >
            {t.label}
          </button>
        ))}
      </div>
      <div style={{ border: '1px solid #eee', borderRadius: '8px' }}>
        {items_${safeId}.map(t => (
          tab_${safeId} === t.id ? (
            <div key={t.id} style={{ padding: '1.5rem' }} dangerouslySetInnerHTML={{ __html: t.content }} />
          ) : null
        ))}
      </div>
    </div>
  );
}`;
}

export function projectToNextJS(project: WebsiteProject): string {
  const gs = project.globalStyles;
  const page = project.pages[0];
  if (!page) {
    return `// No pages found in this project\nexport default function HomePage() { return <p>No pages found.</p>; }\n`;
  }

  const sections = page.sections.filter(s => !s.hidden);
  const { sliders, countdowns, accordions, tabs } = collectInteractiveElements(sections);

  // ── Build interactive component definitions ──────────────────────────────

  const sliderComponents = sliders.map(({ id, config }) => buildSliderComponent(id, config, gs)).join('\n\n');
  const countdownComponents = countdowns.map(({ id, config }) => buildCountdownComponent(id, config, gs)).join('\n\n');
  const accordionComponents = accordions.map(({ id, config }) => buildAccordionComponent(id, config, gs)).join('\n\n');
  const tabComponents = tabs.map(({ id, config }) => buildTabsComponent(id, config, gs)).join('\n\n');

  const interactiveComponents = [sliderComponents, countdownComponents, accordionComponents, tabComponents]
    .filter(Boolean)
    .join('\n\n');

  // ── Build sections JSX ───────────────────────────────────────────────────

  const sectionsJSX = sections.map(sec => {
    const bgStyle: Record<string, string> = {};
    if (sec.background.type === 'color') {
      bgStyle['background'] = sec.background.value;
    } else if (sec.background.type === 'gradient') {
      bgStyle['background'] = sec.background.value;
    } else {
      bgStyle['backgroundImage'] = `url(${sec.background.value})`;
      bgStyle['backgroundSize'] = 'cover';
      bgStyle['backgroundPosition'] = 'center';
    }
    bgStyle['paddingTop'] = `${sec.padding.top}px`;
    bgStyle['paddingBottom'] = `${sec.padding.bottom}px`;

    const maxW = sec.maxWidth === 'xl' ? '1280px' : sec.maxWidth === 'lg' ? '1024px' : sec.maxWidth === 'md' ? '768px' : '100%';

    const colsJSX = sec.columns.map((col, ci) => {
      const elJSX = col.elements.filter(e => !e.hidden).map(el => elementToJSX(el, gs)).join('\n          ');
      return `<div key={${ci}} style={{ flex: '${col.width ? `0 0 ${col.width}%` : '1'}', minWidth: 0 }}>
          ${elJSX}
        </div>`;
    }).join('\n        ');

    return `        {/* ${sec.name} */}
        <section style={${cssToJSXObject(bgStyle)}}>
          <div style={{ maxWidth: '${maxW}', margin: '0 auto', padding: '0 1.5rem', display: 'flex', flexWrap: 'wrap' }}>
            ${colsJSX}
          </div>
        </section>`;
  }).join('\n\n');

  // ── Assemble the full file ───────────────────────────────────────────────

  return `"use client";
// Note: This file was generated by KVL TECH Website Builder
// Drop this into your Next.js app/page.tsx or any route

import React, { useState, useEffect } from 'react';
import Link from 'next/link';

// ─── Global Styles ────────────────────────────────────────────────────────────────────────────────
const COLORS = {
  primary: '${gs.primaryColor}',
  secondary: '${gs.secondaryColor}',
  accent: '${gs.accentColor}',
};

const FONTS = {
  heading: '${gs.headingFont}',
  body: '${gs.bodyFont}',
};

void COLORS; void FONTS; // available for reuse

// ─── Interactive Components ────────────────────────────────────────────────────────────────────
${interactiveComponents || '// No interactive components in this project'}

// ─── Main Page ───────────────────────────────────────────────────────────────────────────────────
export default function HomePage() {
  return (
    <>
      <style>{\`
        @import url('https://fonts.googleapis.com/css2?family=${encodeURIComponent(gs.headingFont)}:wght@400;600;700;800&family=${encodeURIComponent(gs.bodyFont)}:wght@400;500;600&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: '${gs.bodyFont}', sans-serif; font-size: ${gs.baseFontSize}px; color: #333; line-height: 1.6; }
        img { max-width: 100%; }
        a { text-decoration: none; }
        @keyframes marqueeScroll { from { transform: translateX(0) } to { transform: translateX(-50%) } }
        @media (max-width: 768px) {
          nav { flex-wrap: wrap; gap: .5rem; }
          section > div { flex-direction: column !important; }
        }
      \`}</style>
      <main>
${sectionsJSX}
      </main>
    </>
  );
}
`;
}

// ══════════════════════════════════════════════════════════════════════════════
// FUNCTION 2: projectToPHP
// ══════════════════════════════════════════════════════════════════════════════

function elementToHTMLForPHP(el: BuilderElement, gs: GlobalStyles): string {
  const cfg = el.config as Record<string, unknown>;
  const st = cssToString(el.styles || {});
  const wrap = (inner: string, tag = 'div') => `<${tag} style="${st}">${inner}</${tag}>`;

  switch (el.type) {
    case 'heading': {
      const level = (cfg.level as number) || 2;
      const text = (cfg.text as string) || 'Heading';
      return `<h${level} style="font-family:'${gs.headingFont}',sans-serif;${st}">${text}</h${level}>`;
    }
    case 'paragraph': return `<p style="line-height:1.7;${st}">${cfg.text || ''}</p>`;
    case 'richtext': return `<div style="${st}">${cfg.html || ''}</div>`;
    case 'quote': return `<blockquote style="border-left:4px solid ${gs.primaryColor};padding-left:1.5rem;font-style:italic;${st}">${cfg.text || ''}</blockquote>`;
    case 'list': {
      const items = (cfg.items as string[]) || [];
      const tag = cfg.ordered ? 'ol' : 'ul';
      return `<${tag} style="padding-left:1.5rem;line-height:2;${st}">${items.map(i => `<li>${i}</li>`).join('')}</${tag}>`;
    }
    case 'button': {
      const variant = (cfg.variant as string) || 'primary';
      const bgMap: Record<string, string> = { primary: gs.primaryColor, secondary: gs.secondaryColor, outline: 'transparent', ghost: 'transparent', link: 'transparent' };
      const colorMap: Record<string, string> = { primary: '#fff', secondary: '#fff', outline: gs.primaryColor, ghost: gs.primaryColor, link: gs.primaryColor };
      const border = variant === 'outline' ? `2px solid ${gs.primaryColor}` : 'none';
      const size = (cfg.size as string) || 'md';
      const pMap: Record<string, string> = { sm: '6px 16px', md: '10px 24px', lg: '14px 32px' };
      return `<a href="${cfg.href || '#'}" style="display:inline-block;background:${bgMap[variant] || gs.primaryColor};color:${colorMap[variant] || '#fff'};border:${border};padding:${pMap[size] || pMap['md']};border-radius:6px;font-weight:600;text-decoration:none;${st}">${cfg.label || 'Click Here'}</a>`;
    }
    case 'buttongroup': {
      const buttons = (cfg.buttons as Array<{ label: string; href: string; variant: string; size: string }>) || [];
      const btns = buttons.map(btn => {
        const v = btn.variant || 'primary';
        const bgMap: Record<string, string> = { primary: gs.primaryColor, secondary: gs.secondaryColor, outline: 'transparent', ghost: 'transparent', link: 'transparent' };
        const colorMap: Record<string, string> = { primary: '#fff', secondary: '#fff', outline: gs.primaryColor, ghost: gs.primaryColor, link: gs.primaryColor };
        const border = v === 'outline' ? `2px solid ${gs.primaryColor}` : 'none';
        const s = btn.size || 'md';
        const pMap: Record<string, string> = { sm: '6px 16px', md: '10px 24px', lg: '14px 32px' };
        return `<a href="${btn.href || '#'}" style="display:inline-block;background:${bgMap[v] || gs.primaryColor};color:${colorMap[v] || '#fff'};border:${border};padding:${pMap[s] || pMap['md']};border-radius:6px;font-weight:600;text-decoration:none">${btn.label || 'Button'}</a>`;
      }).join('\n');
      return `<div style="display:flex;gap:.75rem;flex-wrap:wrap;align-items:center;${st}">\n${btns}\n</div>`;
    }
    case 'image': return `<div style="${st}"><img src="${cfg.src || ''}" alt="${cfg.alt || ''}" style="width:100%;height:100%;object-fit:${cfg.fit || 'cover'}" /></div>`;
    case 'gallery': {
      const images = (cfg.images as Array<{ src: string; alt: string }>) || [];
      const cols = (cfg.columns as number) || 3;
      const gap = (cfg.gap as number) || 16;
      return `<div style="display:grid;grid-template-columns:repeat(${cols},1fr);gap:${gap}px;${st}">${images.map(img => `<div style="overflow:hidden;border-radius:8px;aspect-ratio:4/3"><img src="${img.src}" alt="${img.alt || ''}" style="width:100%;height:100%;object-fit:cover"/></div>`).join('')}</div>`;
    }
    case 'slider': {
      const slides = (config_as_slides_helper(cfg));
      const sid = `sl_${el.id.replace(/[^a-zA-Z0-9]/g, '_')}`;
      const interval = (cfg.interval as number) || 4000;
      const total = slides.length || 1;
      return `<div id="${sid}" style="position:relative;overflow:hidden;${st}">
  <div id="${sid}_track" style="display:flex;transition:transform .5s ease">
    ${slides.map(s => `<div style="min-width:100%;position:relative"><img src="${s.src}" alt="${s.alt || ''}" style="width:100%;height:500px;object-fit:cover"/>${s.heading ? `<div style="position:absolute;bottom:2rem;left:2rem;color:#fff"><h2 style="font-size:2rem;font-weight:800;text-shadow:0 2px 8px rgba(0,0,0,.5)">${s.heading}</h2>${s.text ? `<p style="margin-top:.5rem;text-shadow:0 1px 4px rgba(0,0,0,.5)">${s.text}</p>` : ''}</div>` : ''}</div>`).join('')}
  </div>
  <button onclick="slPrev_${sid}()" style="position:absolute;left:1rem;top:50%;transform:translateY(-50%);background:rgba(0,0,0,.5);color:#fff;border:none;border-radius:50%;width:40px;height:40px;cursor:pointer;font-size:1.25rem">&#8249;</button>
  <button onclick="slNext_${sid}()" style="position:absolute;right:1rem;top:50%;transform:translateY(-50%);background:rgba(0,0,0,.5);color:#fff;border:none;border-radius:50%;width:40px;height:40px;cursor:pointer;font-size:1.25rem">&#8250;</button>
  <div style="position:absolute;bottom:1rem;left:50%;transform:translateX(-50%);display:flex;gap:.5rem">
    ${slides.map((_, i) => `<button onclick="slGo_${sid}(${i})" id="${sid}_dot${i}" style="width:10px;height:10px;border-radius:50%;border:none;background:${i === 0 ? '#fff' : 'rgba(255,255,255,.5)'};cursor:pointer;padding:0"></button>`).join('')}
  </div>
</div>
<script>
(function(){
  var cur=0,total=${total};
  function go(n){cur=((n%total)+total)%total;document.getElementById('${sid}_track').style.transform='translateX(-'+cur*100+'%)';[...document.querySelectorAll('[id^="${sid}_dot"]')].forEach(function(d,i){d.style.background=i===cur?'#fff':'rgba(255,255,255,.5)';});}
  window.slPrev_${sid}=function(){go(cur-1);};
  window.slNext_${sid}=function(){go(cur+1);};
  window.slGo_${sid}=function(n){go(n);};
  ${cfg.autoPlay !== false ? `setInterval(function(){go(cur+1);},${interval});` : ''}
})();
</script>`;
    }
    case 'marquee': {
      const items = (cfg.items as string[]) || [];
      const sep = (cfg.separator as string) || ' · ';
      const speed = (cfg.speed as number) || 30;
      const text = [...items, ...items].join(sep);
      return `<div style="overflow:hidden;white-space:nowrap;${st}"><span style="display:inline-block;animation:marqueeScroll ${speed}s linear infinite">${text}</span></div>`;
    }
    case 'video': {
      const src = (cfg.src as string) || '';
      if (src.includes('youtube') || src.includes('youtu.be')) {
        const vid = src.includes('youtu.be') ? src.split('youtu.be/')[1]?.split('?')[0] : src.split('v=')[1]?.split('&')[0];
        return `<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;border-radius:8px;${st}"><iframe src="https://www.youtube.com/embed/${vid || ''}" style="position:absolute;top:0;left:0;width:100%;height:100%;border:0" allowfullscreen></iframe></div>`;
      }
      if (src.includes('vimeo.com')) {
        const vid = src.split('vimeo.com/')[1]?.split('?')[0];
        return `<div style="position:relative;padding-bottom:56.25%;height:0;overflow:hidden;border-radius:8px;${st}"><iframe src="https://player.vimeo.com/video/${vid || ''}" style="position:absolute;top:0;left:0;width:100%;height:100%;border:0" allowfullscreen></iframe></div>`;
      }
      return `<video src="${src}" ${cfg.controls !== false ? 'controls' : ''} ${cfg.autoPlay ? 'autoplay' : ''} ${cfg.muted ? 'muted' : ''} ${cfg.loop ? 'loop' : ''} style="width:100%;${st}"></video>`;
    }
    case 'divider': return `<hr style="border:none;border-top:1px solid rgba(0,0,0,0.15);margin:1rem 0;${st}" />`;
    case 'spacer': return `<div style="height:${cfg.height || 48}px"></div>`;
    case 'icon': return `<div style="display:flex;justify-content:center;align-items:center;padding:1rem;${st}"><span style="font-size:${(cfg.size as number) || 48}px;color:${(cfg.color as string) || gs.primaryColor}">&#9733;</span></div>`;
    case 'iconbox': return wrap(`<div style="text-align:${cfg.align || 'center'};padding:2rem 1.5rem"><div style="font-size:2.5rem;margin-bottom:1rem">${cfg.icon || '★'}</div><h4 style="font-weight:700;font-size:1.25rem;margin-bottom:.5rem;font-family:'${gs.headingFont}',sans-serif">${cfg.title || ''}</h4><p style="color:#666;line-height:1.7">${cfg.description || ''}</p></div>`);
    case 'card': {
      const title = (cfg.title as string) || 'Card Title';
      const desc = (cfg.description as string) || '';
      const image = cfg.image as string | undefined;
      const link = cfg.link as string | undefined;
      const badge = cfg.badge as string | undefined;
      return `<div style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.08);${st}">${image ? `<div style="aspect-ratio:16/9;overflow:hidden"><img src="${image}" alt="${title}" style="width:100%;height:100%;object-fit:cover"/></div>` : ''}<div style="padding:1.5rem">${badge ? `<span style="display:inline-block;background:${gs.primaryColor};color:#fff;font-size:.7rem;font-weight:700;padding:2px 10px;border-radius:999px;margin-bottom:.75rem;text-transform:uppercase">${badge}</span>` : ''}<h4 style="font-weight:700;font-size:1.1rem;margin-bottom:.5rem">${title}</h4><p style="color:#666;line-height:1.6;font-size:.9rem">${desc}</p>${link ? `<a href="${link}" style="display:inline-block;margin-top:1rem;color:${gs.primaryColor};font-weight:600;font-size:.875rem;text-decoration:none">Learn more &rarr;</a>` : ''}</div></div>`;
    }
    case 'counter': {
      const items = (cfg.items as Array<{ value: number; label: string; prefix?: string; suffix?: string }>) || [];
      return wrap(`<div style="display:flex;flex-wrap:wrap;justify-content:center;gap:3rem;padding:2rem">${items.map(it => `<div style="text-align:center"><div style="font-size:3rem;font-weight:800;color:${gs.primaryColor}">${it.prefix || ''}${it.value}${it.suffix || ''}</div><div style="color:#666;margin-top:.5rem">${it.label}</div></div>`).join('')}</div>`);
    }
    case 'testimonial': {
      const rating = (cfg.rating as number) || 5;
      return wrap(`<div style="max-width:700px;margin:0 auto;background:#fff;border-radius:12px;padding:2.5rem;box-shadow:0 4px 24px rgba(0,0,0,.08)"><div style="color:#F59E0B;font-size:1.25rem;margin-bottom:1rem">${'★'.repeat(Math.min(5, Math.max(0, rating)))}</div><p style="font-size:1.1rem;color:#555;font-style:italic;margin-bottom:1.5rem">&ldquo;${cfg.text || ''}&rdquo;</p><strong>${cfg.name || ''}</strong> <span style="color:#888;font-size:.875rem">&middot; ${cfg.role || ''}</span></div>`);
    }
    case 'pricing': {
      const plans = (cfg.plans as Array<{ name: string; price: string; period: string; features: string[]; cta: { label: string; href: string }; highlighted: boolean; badge?: string }>) || [];
      return wrap(`<div style="display:flex;flex-wrap:wrap;gap:1.5rem;justify-content:center;padding:2rem 0">${plans.map(p => `<div style="flex:1 1 280px;max-width:320px;background:${p.highlighted ? gs.secondaryColor : '#fff'};color:${p.highlighted ? '#fff' : '#333'};border:${p.highlighted ? `2px solid ${gs.primaryColor}` : '1px solid #eee'};border-radius:16px;padding:2rem;position:relative">${p.badge ? `<span style="position:absolute;top:-12px;right:16px;background:${gs.primaryColor};color:#fff;padding:2px 12px;border-radius:999px;font-size:.75rem;font-weight:700">${p.badge}</span>` : ''}<h3 style="font-size:1.25rem;font-weight:700;margin-bottom:.5rem">${p.name}</h3><div style="font-size:2.5rem;font-weight:800;color:${gs.primaryColor};margin-bottom:.25rem">${p.price}</div><div style="color:#888;font-size:.875rem;margin-bottom:1.5rem">${p.period}</div><ul style="list-style:none;padding:0;margin-bottom:2rem">${(p.features || []).map(f => `<li style="padding:.25rem 0">&#10003; ${f}</li>`).join('')}</ul><a href="${p.cta?.href || '#'}" style="display:block;text-align:center;padding:.75rem;border-radius:8px;background:${p.highlighted ? gs.primaryColor : 'transparent'};color:${p.highlighted ? gs.secondaryColor : gs.primaryColor};border:2px solid ${gs.primaryColor};font-weight:700;text-decoration:none">${p.cta?.label || 'Get Started'}</a></div>`).join('')}</div>`);
    }
    case 'accordion': {
      const items = (cfg.items as Array<{ id: string; question: string; answer: string }>) || [];
      return wrap(`<div style="max-width:800px;margin:0 auto">${items.map((it, i) => `<details style="border:1px solid #eee;border-radius:8px;margin-bottom:.5rem;overflow:hidden"${i === 0 ? ' open' : ''}><summary style="padding:1rem 1.5rem;cursor:pointer;font-weight:600;font-size:1rem;list-style:none">${it.question}</summary><div style="padding:1rem 1.5rem;border-top:1px solid #eee;color:#555;line-height:1.7">${it.answer}</div></details>`).join('')}</div>`);
    }
    case 'tabs': {
      const items = (cfg.items as Array<{ id: string; label: string; content: string }>) || [];
      const tabBtns = items.map((t, i) => `<button onclick="(function(btn){document.querySelectorAll('.tc_${el.id.replace(/[^a-zA-Z0-9]/g, '_')}').forEach(function(x){x.style.display='none'});document.getElementById('tp_${el.id.replace(/[^a-zA-Z0-9]/g, '_')}_${t.id.replace(/[^a-zA-Z0-9]/g, '_')}').style.display='block';btn.parentElement.querySelectorAll('button').forEach(function(b){b.style.background='transparent';b.style.color='#555'});btn.style.background='${gs.primaryColor}';btn.style.color='#fff'})(this)" style="padding:.5rem 1.5rem;border:none;border-radius:6px;cursor:pointer;font-weight:600;background:${i === 0 ? gs.primaryColor : 'transparent'};color:${i === 0 ? '#fff' : '#555'}">${t.label}</button>`).join('');
      const panels = items.map((t, i) => `<div id="tp_${el.id.replace(/[^a-zA-Z0-9]/g, '_')}_${t.id.replace(/[^a-zA-Z0-9]/g, '_')}" class="tc_${el.id.replace(/[^a-zA-Z0-9]/g, '_')}" style="padding:1.5rem;display:${i === 0 ? 'block' : 'none'}">${t.content}</div>`).join('');
      return wrap(`<div><div style="display:flex;gap:.5rem;margin-bottom:1rem;flex-wrap:wrap">${tabBtns}</div><div style="border:1px solid #eee;border-radius:8px">${panels}</div></div>`);
    }
    case 'form': {
      const fields = (cfg.fields as Array<{ id: string; type: string; label: string; placeholder?: string; required?: boolean; options?: string[] }>) || [];
      const inputs = fields.map(f => {
        const req = f.required ? ' required' : '';
        if (f.type === 'textarea') return `<div style="margin-bottom:1rem"><label style="display:block;margin-bottom:.25rem;font-weight:500">${f.label}</label><textarea name="${f.id}" placeholder="${f.placeholder || ''}"${req} rows="4" style="width:100%;padding:.5rem .75rem;border:1px solid #ddd;border-radius:6px;font-family:inherit;resize:vertical"></textarea></div>`;
        if (f.type === 'select') return `<div style="margin-bottom:1rem"><label style="display:block;margin-bottom:.25rem;font-weight:500">${f.label}</label><select name="${f.id}"${req} style="width:100%;padding:.5rem .75rem;border:1px solid #ddd;border-radius:6px">${(f.options || []).map(o => `<option>${o}</option>`).join('')}</select></div>`;
        if (f.type === 'checkbox') return `<div style="margin-bottom:1rem"><label style="display:flex;align-items:center;gap:.5rem;cursor:pointer"><input type="checkbox" name="${f.id}" /><span style="font-size:.875rem">${f.placeholder || f.label}</span></label></div>`;
        return `<div style="margin-bottom:1rem"><label style="display:block;margin-bottom:.25rem;font-weight:500">${f.label}</label><input type="${f.type}" name="${f.id}" placeholder="${f.placeholder || ''}"${req} style="width:100%;padding:.5rem .75rem;border:1px solid #ddd;border-radius:6px" /></div>`;
      }).join('');
      // PHP self-submitting form
      return `<div style="${st}">
<?php if ($form_success): ?>
  <p style="color:green;font-size:1.1rem;padding:1rem;background:#f0fff4;border-radius:8px;margin-bottom:1rem"><?php echo htmlspecialchars($success_message); ?></p>
<?php elseif ($form_error): ?>
  <p style="color:red;padding:1rem;background:#fff5f5;border-radius:8px;margin-bottom:1rem"><?php echo htmlspecialchars($form_error); ?></p>
<?php endif; ?>
<form method="POST" action="<?php echo htmlspecialchars($_SERVER['PHP_SELF']); ?>" style="max-width:600px;margin:0 auto">
  <input type="hidden" name="_form" value="1">
  ${inputs}
  <button type="submit" style="background:${gs.primaryColor};color:#fff;border:none;padding:.75rem 2.5rem;border-radius:8px;font-weight:700;font-size:1rem;cursor:pointer">${cfg.submitLabel || 'Send'}</button>
</form>
</div>`;
    }
    case 'social': {
      const links = (cfg.links as Array<{ platform: string; url: string }>) || [];
      const colors: Record<string, string> = { facebook: '#1877F2', instagram: '#E4405F', twitter: '#1DA1F2', youtube: '#FF0000', linkedin: '#0A66C2', whatsapp: '#25D366', tiktok: '#010101', pinterest: '#E60023' };
      const icons: Record<string, string> = { facebook: 'f', instagram: '&#x1F4F7;', twitter: 'X', youtube: '&#x25B6;', linkedin: 'in', whatsapp: 'W', tiktok: '&#x266A;', pinterest: 'P' };
      return `<div style="display:flex;gap:.75rem;flex-wrap:wrap;justify-content:center;${st}">${links.map(l => `<a href="${l.url}" style="width:44px;height:44px;border-radius:50%;background:${colors[l.platform] || '#666'};display:flex;align-items:center;justify-content:center;color:#fff;font-weight:700;text-decoration:none;font-size:.875rem">${icons[l.platform] || (l.platform[0]?.toUpperCase() || '?')}</a>`).join('')}</div>`;
    }
    case 'map': {
      const addr = encodeURIComponent((cfg.address as string) || 'India');
      const zoom = (cfg.zoom as number) || 14;
      const height = (cfg.height as number) || 400;
      return `<div style="border-radius:12px;overflow:hidden;${st}"><iframe src="https://maps.google.com/maps?q=${addr}&output=embed&z=${zoom}" width="100%" height="${height}" style="border:0" allowfullscreen loading="lazy"></iframe></div>`;
    }
    case 'navbar': {
      const links = (cfg.links as Array<{ label: string; href: string }>) || [];
      return `<nav style="display:flex;align-items:center;justify-content:space-between;padding:1rem 2rem;background:${gs.secondaryColor};color:#fff;${st}"><span style="font-weight:800;font-size:1.25rem;color:${gs.primaryColor};font-family:'${gs.headingFont}',sans-serif"><?php echo htmlspecialchars($site_name); ?></span><div style="display:flex;gap:1.5rem;align-items:center">${links.map(l => `<a href="${l.href}" style="color:#fff;text-decoration:none;font-size:.9rem;font-weight:500">${l.label}</a>`).join('')}</div></nav>`;
    }
    case 'footer': {
      const columns = (cfg.columns as Array<{ heading: string; links: Array<{ label: string; href: string }> }>) || [];
      const socials = (cfg.socials as Array<{ platform: string; url: string }>) || [];
      const socColors: Record<string, string> = { facebook: '#1877F2', instagram: '#E4405F', twitter: '#1DA1F2', youtube: '#FF0000', linkedin: '#0A66C2', whatsapp: '#25D366' };
      return `<footer style="background:${gs.secondaryColor};color:#fff;padding:3rem 2rem 1.5rem;${st}"><div style="max-width:1280px;margin:0 auto"><div style="display:flex;flex-wrap:wrap;gap:2rem;margin-bottom:2rem">${columns.map(col => `<div style="flex:1 1 160px"><h5 style="font-weight:700;margin-bottom:1rem;color:${gs.primaryColor}">${col.heading}</h5><ul style="list-style:none;padding:0">${col.links.map(l => `<li style="margin-bottom:.5rem"><a href="${l.href}" style="color:#aaa;text-decoration:none;font-size:.875rem">${l.label}</a></li>`).join('')}</ul></div>`).join('')}</div>${cfg.tagline ? `<p style="color:#888;margin-bottom:1rem;font-size:.875rem">${cfg.tagline}</p>` : ''}<div style="display:flex;gap:.5rem;margin-bottom:1rem">${socials.map(s => `<a href="${s.url}" style="width:36px;height:36px;border-radius:50%;background:${socColors[s.platform] || '#666'};display:inline-flex;align-items:center;justify-content:center;color:#fff;text-decoration:none;font-size:.75rem">${s.platform[0]?.toUpperCase() || '?'}</a>`).join('')}</div><div style="border-top:1px solid rgba(255,255,255,.1);padding-top:1rem;color:#555;font-size:.8rem">&copy; ${cfg.copyright || ''}</div></div></footer>`;
    }
    case 'hero': {
      const cta = cfg.cta as { label: string; href: string } | undefined;
      const cta2 = cfg.secondaryCta as { label: string; href: string } | undefined;
      const align = (cfg.align as string) || 'center';
      const overlay = (cfg.overlay as number) || 50;
      const bgImg = cfg.bgImage as string | undefined;
      const justifyContent = align === 'center' ? 'center' : align === 'right' ? 'flex-end' : 'flex-start';
      return `<div style="position:relative;min-height:80vh;display:flex;align-items:center;justify-content:center;overflow:hidden;${st}">${bgImg ? `<img src="${bgImg}" alt="" style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover"/>` : ''}<div style="position:absolute;inset:0;background:rgba(11,20,55,${overlay / 100})"></div><div style="position:relative;text-align:${align};color:#fff;padding:4rem 2rem;max-width:900px;width:100%">${cfg.subheading ? `<p style="color:${gs.primaryColor};font-weight:600;letter-spacing:.1em;margin-bottom:1rem;text-transform:uppercase;font-size:.875rem">${cfg.subheading}</p>` : ''}<h1 style="font-size:clamp(2rem,5vw,4rem);font-weight:800;line-height:1.1;margin-bottom:1.5rem;font-family:'${gs.headingFont}',sans-serif">${cfg.heading || 'Welcome'}</h1>${cfg.text ? `<p style="font-size:1.25rem;opacity:.85;margin-bottom:2rem;max-width:600px;margin-left:auto;margin-right:auto">${cfg.text}</p>` : ''}<div style="display:flex;gap:1rem;justify-content:${justifyContent};flex-wrap:wrap">${cta ? `<a href="${cta.href}" style="background:${gs.primaryColor};color:#fff;padding:.875rem 2.5rem;border-radius:8px;font-weight:700;text-decoration:none;font-size:1.1rem">${cta.label}</a>` : ''} ${cta2 ? `<a href="${cta2.href}" style="border:2px solid rgba(255,255,255,.6);color:#fff;padding:.875rem 2.5rem;border-radius:8px;font-weight:700;text-decoration:none;font-size:1.1rem">${cta2.label}</a>` : ''}</div></div></div>`;
    }
    case 'cta': {
      const cta = cfg.cta as { label: string; href: string } | undefined;
      return `<div style="background:${cfg.bgColor || gs.secondaryColor};color:#fff;text-align:center;padding:4rem 2rem;${st}"><h2 style="font-size:2rem;font-weight:700;margin-bottom:1rem;font-family:'${gs.headingFont}',sans-serif">${cfg.heading || ''}</h2><p style="opacity:.8;margin-bottom:2rem;font-size:1.1rem">${cfg.text || ''}</p>${cta ? `<a href="${cta.href}" style="background:${gs.primaryColor};color:#fff;padding:.875rem 2.5rem;border-radius:8px;font-weight:700;text-decoration:none;font-size:1.1rem">${cta.label}</a>` : ''}</div>`;
    }
    case 'countdown': {
      const cdId = `cd_${el.id.replace(/[^a-zA-Z0-9]/g, '_')}`;
      const targetDate = (cfg.targetDate as string) || '2026-12-31';
      const label = (cfg.label as string) || '';
      return `<div id="${cdId}" style="text-align:center;padding:2rem;${st}">${label ? `<p style="margin-bottom:1rem;font-weight:600;color:${gs.primaryColor}">${label}</p>` : ''}<div style="display:flex;gap:1rem;justify-content:center">${['days', 'hours', 'minutes', 'seconds'].map(u => `<div style="background:${gs.secondaryColor};color:#fff;border-radius:12px;padding:1rem 1.5rem;min-width:80px"><div class="${cdId}_${u}" style="font-size:2.5rem;font-weight:800;color:${gs.primaryColor}">00</div><div style="font-size:.75rem;opacity:.7;text-transform:capitalize">${u}</div></div>`).join('')}</div></div>
<script>
(function(){var t=new Date("${targetDate}").getTime();function u(){var n=t-Date.now();if(n<0)return;document.querySelector(".${cdId}_days").textContent=String(Math.floor(n/86400000)).padStart(2,"0");document.querySelector(".${cdId}_hours").textContent=String(Math.floor((n%86400000)/3600000)).padStart(2,"0");document.querySelector(".${cdId}_minutes").textContent=String(Math.floor((n%3600000)/60000)).padStart(2,"0");document.querySelector(".${cdId}_seconds").textContent=String(Math.floor((n%60000)/1000)).padStart(2,"0");}u();setInterval(u,1000);})();
</script>`;
    }
    case 'progress': {
      const items = (cfg.items as Array<{ label: string; value: number; color?: string }>) || [];
      return wrap(`<div style="max-width:700px;margin:0 auto;padding:1rem">${items.map(it => `<div style="margin-bottom:1.5rem"><div style="display:flex;justify-content:space-between;margin-bottom:.5rem"><span style="font-weight:600">${it.label}</span><span style="color:${it.color || gs.primaryColor};font-weight:700">${it.value}%</span></div><div style="background:#eee;border-radius:999px;height:8px"><div style="background:${it.color || gs.primaryColor};border-radius:999px;height:8px;width:${it.value}%;transition:width 1s"></div></div></div>`).join('')}</div>`);
    }
    default:
      return `<div style="padding:1rem;border:1px dashed #ccc;color:#999;text-align:center"><!-- ${el.type} --></div>`;
  }
}

// Small helper to avoid inline complex type assertion
function config_as_slides_helper(cfg: Record<string, unknown>): Array<{ src: string; alt?: string; heading?: string; text?: string }> {
  return (cfg.slides as Array<{ src: string; alt?: string; heading?: string; text?: string }>) || [];
}

function sectionToPHP(sec: Section, gs: GlobalStyles, index: number): string {
  const bgStyle = sec.background.type === 'color'
    ? `background:${sec.background.value}`
    : sec.background.type === 'gradient'
    ? `background:${sec.background.value}`
    : `background-image:url(${sec.background.value});background-size:cover;background-position:center`;

  const maxW = sec.maxWidth === 'xl' ? '1280px' : sec.maxWidth === 'lg' ? '1024px' : sec.maxWidth === 'md' ? '768px' : '100%';

  const cols = sec.columns.map(col => {
    const elHTML = col.elements.filter(e => !e.hidden).map(el => elementToHTMLForPHP(el, gs)).join('\n');
    return `    <div style="flex:${col.width ? `0 0 ${col.width}%` : '1'};min-width:0">\n${elHTML}\n    </div>`;
  }).join('\n');

  return `<?php /* Section ${index + 1}: ${sec.name} */ ?>
<section style="${bgStyle};padding:${sec.padding.top}px 0 ${sec.padding.bottom}px">
  <div style="max-width:${maxW};margin:0 auto;padding:0 1.5rem;display:flex;flex-wrap:wrap">
${cols}
  </div>
</section>`;
}

export function projectToPHP(project: WebsiteProject): string {
  const gs = project.globalStyles;
  const page = project.pages[0];
  if (!page) {
    return '<?php /* No pages found */ ?>\n<!DOCTYPE html><html><body><p>No pages found.</p></body></html>\n';
  }

  const sections = page.sections.filter(s => !s.hidden);
  const pageTitle = page.seo.title || project.name;
  const pageDesc = page.seo.description || '';
  const pageKeywords = page.seo.keywords || '';

  const bodySections = sections.map((sec, i) => sectionToPHP(sec, gs, i)).join('\n\n');

  const headingFontEnc = encodeURIComponent(gs.headingFont);
  const bodyFontEnc = encodeURIComponent(gs.bodyFont);

  return `<?php
// Generated by KVL TECH Website Builder
// Project: ${project.name}

// ─── Site Variables ───────────────────────────────────────────────────────────
$site_name        = ${JSON.stringify(project.name)};
$site_description = ${JSON.stringify(pageDesc)};
$site_title       = ${JSON.stringify(pageTitle)};
$primary_color    = ${JSON.stringify(gs.primaryColor)};
$secondary_color  = ${JSON.stringify(gs.secondaryColor)};
$accent_color     = ${JSON.stringify(gs.accentColor)};
$heading_font     = ${JSON.stringify(gs.headingFont)};
$body_font        = ${JSON.stringify(gs.bodyFont)};
$success_message  = "Thank you! We will contact you soon.";

// ─── Contact Form Handler ─────────────────────────────────────────────────────
$form_success = false;
$form_error   = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['_form'])) {
    $name    = filter_input(INPUT_POST, 'name',    FILTER_SANITIZE_SPECIAL_CHARS);
    $email   = filter_input(INPUT_POST, 'email',   FILTER_SANITIZE_EMAIL);
    $message = filter_input(INPUT_POST, 'message', FILTER_SANITIZE_SPECIAL_CHARS);
    if ($name && $email && $message) {
        // Configure mail() or use an SMTP library (PHPMailer, etc.) as needed:
        // mail('your@email.com', 'Contact: ' . $site_name, $message, 'From: ' . $email);
        $form_success = true;
    } else {
        $form_error = 'Please fill in all required fields.';
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo htmlspecialchars($site_title); ?></title>
  <meta name="description" content="<?php echo htmlspecialchars($site_description); ?>">
${pageKeywords ? `  <meta name="keywords" content="${pageKeywords}">` : ''}
  <link href="https://fonts.googleapis.com/css2?family=${headingFontEnc}:wght@400;600;700;800&family=${bodyFontEnc}:wght@400;500;600&display=swap" rel="stylesheet">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: '<?php echo htmlspecialchars($body_font); ?>', sans-serif; font-size: ${gs.baseFontSize}px; color: #333; line-height: 1.6; }
    img { max-width: 100%; }
    a { text-decoration: none; }
    details > summary { list-style: none; }
    details > summary::-webkit-details-marker { display: none; }
    @keyframes marqueeScroll { from { transform: translateX(0); } to { transform: translateX(-50%); } }
    @media (max-width: 768px) {
      nav { flex-wrap: wrap; gap: .5rem; }
      nav div { display: none; }
      section > div { flex-direction: column !important; }
    }
${project.customCSS ? `    /* Custom CSS */\n    ${project.customCSS}` : ''}
  </style>
</head>
<body>

${bodySections}

</body>
</html>
`;
}

// ══════════════════════════════════════════════════════════════════════════════
// FUNCTION 3: projectToHTML  (plain HTML export, same as the PHP body without PHP wrapping)
// ══════════════════════════════════════════════════════════════════════════════

function sectionToHTML(sec: Section, gs: GlobalStyles): string {
  const bgStyle = sec.background.type === 'color'
    ? `background:${sec.background.value}`
    : sec.background.type === 'gradient'
    ? `background:${sec.background.value}`
    : `background-image:url(${sec.background.value});background-size:cover;background-position:center`;

  const maxW = sec.maxWidth === 'xl' ? '1280px' : sec.maxWidth === 'lg' ? '1024px' : sec.maxWidth === 'md' ? '768px' : '100%';

  const cols = sec.columns.map(col => {
    const elHTML = col.elements.filter(e => !e.hidden).map(el => elementToHTMLForPHP(el, gs)).join('\n');
    return `<div style="flex:${col.width ? `0 0 ${col.width}%` : '1'};min-width:0">${elHTML}</div>`;
  }).join('\n');

  return `<section style="${bgStyle};padding:${sec.padding.top}px 0 ${sec.padding.bottom}px"><div style="max-width:${maxW};margin:0 auto;padding:0 1.5rem;display:flex;flex-wrap:wrap">${cols}</div></section>`;
}

export function projectToHTML(project: WebsiteProject): string {
  const gs = project.globalStyles;
  const page = project.pages[0];
  if (!page) return '<!DOCTYPE html><html><body><p>No pages found.</p></body></html>';

  const sections = page.sections.filter(s => !s.hidden);
  const body = sections.map(sec => sectionToHTML(sec, gs)).join('\n');
  const pageTitle = page.seo.title || project.name;
  const pageDesc = page.seo.description || '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${pageTitle}</title>
<meta name="description" content="${pageDesc}"/>
<link href="https://fonts.googleapis.com/css2?family=${encodeURIComponent(gs.headingFont)}:wght@400;600;700;800&family=${encodeURIComponent(gs.bodyFont)}:wght@400;500;600&display=swap" rel="stylesheet"/>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'${gs.bodyFont}',sans-serif;font-size:${gs.baseFontSize}px;color:#333;line-height:1.6}
img{max-width:100%}
a{text-decoration:none}
details>summary{list-style:none}details>summary::-webkit-details-marker{display:none}
@keyframes marqueeScroll{from{transform:translateX(0)}to{transform:translateX(-50%)}}
@media(max-width:768px){
  nav{flex-wrap:wrap;gap:.5rem}
  nav div{display:none}
  section>div{flex-direction:column!important}
}
${project.customCSS || ''}
</style>
</head>
<body>
${body}
</body>
</html>`;
}
